#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0
#
# syscall_gen.py — agentrt-linux syscall 契约代码生成器
#
# 解析 syscall.xml 契约源（R-01 SSoT），生成 C UAPI 头文件 syscall_gen.h。
#
# 输入: include/uapi/linux/airymax/syscall.xml
# 输出: include/uapi/linux/airymax/syscall_gen.h
#
# 生成内容：
#   a. #define AIRY_SYS_* 宏（内部编号 0-3）
#   b. #define __NR_airy_sys_* 宏（Linux 注册号 = number + 548）
#   c. 函数原型声明（含 Doxygen 注释）
#   d. 文件头部 @generated 标记
#
# 使用 Python 标准库（xml.etree.ElementTree），不依赖第三方库。
#
# Copyright (c) 2025-2026 SPHARX Ltd. All Rights Reserved.
# Generator version: 1.0.1

import argparse
import difflib
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

GENERATOR_VERSION = "1.0.1"

# 脚本所在目录与仓库根（agentrt-linux/）
SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parents[1]

DEFAULT_INPUT = REPO_ROOT / "kernel" / "include" / "uapi" / "linux" / "airymax" / "syscall.xml"
DEFAULT_OUTPUT = REPO_ROOT / "kernel" / "include" / "uapi" / "linux" / "airymax" / "syscall_gen.h"


def parse_xml(xml_path):
    """解析 syscall.xml，返回结构化数据字典。

    数据结构：
      {
        version, core_count, reserved_count, total_slots, linux_base,
        meta: { generator, generator_version, schema_version, prefix_symbol, prefix_function },
        syscalls: [ { name, number, signature, capability_required, flags,
                      category, since, stability, doc, symbol_macro } ],
        reserved: [ { from, to, reason } ],
      }
    """
    tree = ET.parse(str(xml_path))
    root = tree.getroot()

    version = root.get("version", "0x0100")
    core_count = int(root.get("core_count", "0"))
    reserved_count = int(root.get("reserved_count", "0"))
    total_slots = int(root.get("total_slots", "0"))
    linux_base = int(root.get("linux_base", "548"))

    # 解析 meta 元数据
    meta = {}
    meta_elem = root.find("meta")
    if meta_elem is not None:
        for child in meta_elem:
            meta[child.tag] = (child.text or "").strip()
    prefix_symbol = meta.get("prefix_symbol", "AIRY_SYS_")
    prefix_function = meta.get("prefix_function", "airy_sys_")
    # 内部索引宏前缀（与 [SC] syscalls.h 的实际 syscall 号宏命名空间分离）
    prefix_index = meta.get("prefix_index", "AIRY_SYS_IDX_")

    # 解析核心 syscall 列表
    syscalls = []
    for sc_elem in root.findall("syscall"):
        name = (sc_elem.findtext("name") or "").strip()
        number = int((sc_elem.findtext("number") or "0").strip())
        signature = (sc_elem.findtext("signature") or "").strip()
        cap_req = (sc_elem.findtext("capability_required") or "").strip()
        flags = (sc_elem.findtext("flags") or "").strip()
        category = (sc_elem.findtext("category") or "").strip()
        since = (sc_elem.findtext("since") or "").strip()
        stability = (sc_elem.findtext("stability") or "").strip()
        doc = (sc_elem.findtext("doc") or "").strip()

        # 推导符号宏：airy_sys_call -> AIRY_SYS_CALL（实际 syscall 号）
        # 推导索引宏：airy_sys_call -> AIRY_SYS_IDX_CALL（codegen 内部索引）
        # 两者命名空间分离，避免与 [SC] syscalls.h 的 AIRY_SYS_CALL=548 冲突
        suffix = name[len(prefix_function):] if name.startswith(prefix_function) else name
        symbol_macro = prefix_symbol + suffix.upper()
        index_macro = prefix_index + suffix.upper()

        syscalls.append({
            "name": name,
            "number": number,
            "signature": signature,
            "capability_required": cap_req,
            "flags": flags,
            "category": category,
            "since": since,
            "stability": stability,
            "doc": doc,
            "symbol_macro": symbol_macro,
            "index_macro": index_macro,
        })

    # 解析预留段
    reserved = []
    for r_elem in root.findall("reserved"):
        reserved.append({
            "from": int(r_elem.get("from", "0")),
            "to": int(r_elem.get("to", "0")),
            "reason": r_elem.get("reason", "future extension"),
        })

    return {
        "version": version,
        "core_count": core_count,
        "reserved_count": reserved_count,
        "total_slots": total_slots,
        "linux_base": linux_base,
        "meta": meta,
        "syscalls": syscalls,
        "reserved": reserved,
    }


def render_c_header(data):
    """将解析数据渲染为 C UAPI 头文件内容（字符串）。

    生成的头文件结构：
      1. SPDX + @generated 头部
      2. include guard
      3. 基址与槽位计数宏
      4. AIRY_SYS_* 内部编号宏（0-3）
      5. __NR_airy_sys_* Linux 注册号宏（number + 548）
      6. 预留槽位编号宏
      7. 函数原型声明（含 Doxygen 注释）
      8. include guard 结束
    """
    linux_base = data["linux_base"]
    lines = []

    # ── 1. 文件头部 ──
    lines.append("/* SPDX-License-Identifier: GPL-2.0-only WITH Linux-syscall-note */")
    lines.append("/* @generated by syscall_gen.py v%s from syscall.xml — DO NOT EDIT */" % GENERATOR_VERSION)
    lines.append("/* Source: include/uapi/linux/airymax/syscall.xml (R-01 SSoT) */")
    lines.append("/*")
    lines.append(" * Copyright (c) 2025-2026 SPHARX Ltd. All Rights Reserved.")
    lines.append(" *")
    lines.append(" * agentrt-linux (AirymaxOS) Agent 专用系统调用编号定义（生成产物）")
    lines.append(" *")
    lines.append(" * 编号规则:")
    lines.append(" *   - 起始编号 %d（避开 Linux 标准 0-511 + x86_64 x32 区域 512-547）" % linux_base)
    lines.append(" *   - %d 核心 syscall + %d 预留 = %d 槽位（v1.0.1 Capability Folding）"
                 % (data["core_count"], data["reserved_count"], data["total_slots"]))
    lines.append(" *   - 编号在 MAJOR 版本内不可变更（OS-IRON-001）")
    lines.append(" *   - 废弃编号保留，返回 -AIRY_ENOSYS")
    lines.append(" */")
    lines.append("")

    # ── 2. include guard ──
    lines.append("#ifndef AIRY_SYSCALL_GEN_H")
    lines.append("#define AIRY_SYSCALL_GEN_H")
    lines.append("")
    lines.append("#include <linux/airymax/uapi_compat.h>")
    lines.append("")

    # ── 3. 基址与槽位计数 ──
    lines.append("/* ===== 基址与槽位计数 ===== */")
    lines.append("#define AIRY_SYS_BASE\t\t%d  /* agentrt-linux 专用编号起始 */" % linux_base)
    lines.append("#define AIRY_SYS_NR_CORE\t%d    /* 核心 syscall 数 */" % data["core_count"])
    lines.append("#define AIRY_SYS_NR_RESERVED\t%d   /* 预留槽位数 */" % data["reserved_count"])
    lines.append("#define AIRY_SYS_NR_TOTAL\t%d   /* 总槽位数（%d-%d） */"
                 % (data["total_slots"], linux_base, linux_base + data["total_slots"] - 1))
    lines.append("")

    # ── 4. 内部索引宏（AIRY_SYS_IDX_* = 内部索引 0-3，仅 codegen 内部使用） ──
    lines.append("/* ===== 内部索引编号（0-%d，仅 codegen 内部使用） =====" % (data["core_count"] - 1))
    lines.append(" * 注意：这些是 codegen 内部索引，与 [SC] syscalls.h 中的")
    lines.append(" * AIRY_SYS_CALL=548 等实际系统调用号不同。为避免命名冲突，")
    lines.append(" * 内部索引使用 AIRY_SYS_IDX_* 前缀。")
    lines.append(" */")
    for sc in data["syscalls"]:
        lines.append("#define %s\t%d  /* %s */" % (sc["index_macro"], sc["number"], sc["name"]))
    lines.append("")

    # ── 5. Linux 注册号宏（__NR_airy_sys_* = 内部编号 + linux_base） ──
    lines.append("/* ===== Linux 注册号（内部编号 + %d） ===== */" % linux_base)
    for sc in data["syscalls"]:
        linux_nr = sc["number"] + linux_base
        lines.append("#define __NR_%s\t%d" % (sc["name"], linux_nr))
    lines.append("")

    # ── 6. 预留槽位编号宏 ──
    if data["reserved"]:
        lines.append("/* ===== 预留槽位（不生成函数声明） ===== */")
        for r in data["reserved"]:
            for i in range(r["from"], r["to"] + 1):
                lines.append("#define AIRY_SYS_RESERVED_%d\t%d  /* Linux %d */"
                             % (i, i, i + linux_base))
        lines.append("")

    # ── 7. 函数原型声明 ──
    lines.append("/* ===== 函数原型 ===== */")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")
    for sc in data["syscalls"]:
        lines.append("/**")
        # Doxygen 描述行：超过 80 字符则在最后一个空格（不超过 80）处换行
        doc_prefix = " * %s - " % sc["name"]
        doc_full = doc_prefix + sc["doc"]
        if len(doc_full) <= 80:
            lines.append(doc_full)
        else:
            # 在 80 字符附近找空格换行
            split_pos = 80
            while split_pos > len(doc_prefix) and doc_full[split_pos] != ' ':
                split_pos -= 1
            if split_pos <= len(doc_prefix):
                # 找不到合适空格，保持单行
                lines.append(doc_full)
            else:
                lines.append(doc_full[:split_pos])
                lines.append(" * " + doc_full[split_pos + 1:])
        lines.append(" *")
        lines.append(" * Return: 0 on success, negative errno on failure.")
        lines.append(" *")
        lines.append(" * @since %s" % sc["since"])
        lines.append(" * @stability %s" % sc["stability"])
        if sc["capability_required"]:
            lines.append(" * @capability %s" % sc["capability_required"])
        lines.append(" */")
        # 函数原型：超过 80 字符则在最后一个逗号后换行
        proto_line = "AIRY_API int %s(%s);" % (sc["name"], sc["signature"])
        if len(proto_line) <= 80:
            lines.append(proto_line)
        else:
            # 在最后一个逗号后换行
            last_comma = sc["signature"].rfind(",")
            if last_comma == -1:
                lines.append(proto_line)
            else:
                first_part = sc["signature"][:last_comma + 1]
                second_part = sc["signature"][last_comma + 2:]  # skip ", "
                lines.append("AIRY_API int %s(%s" % (sc["name"], first_part))
                lines.append("\t\t\t\t%s);" % second_part)
        lines.append("")

    # ── 8. include guard 结束 ──
    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")
    lines.append("")
    lines.append("#endif /* AIRY_SYSCALL_GEN_H */")
    lines.append("")

    return "\n".join(lines)


def render_syscall_tbl(data):
    """将解析数据渲染为 syscall_64.tbl Airymax 段片段（字符串）。

    生成格式（插入 syscall_64.tbl 的 Airymax 段）：
      #
      # Airymax syscalls (548-551)
      # v1.0.1: 统一使用 548 起始...
      #
      548\tcommon\tairy_sys_call\t\tsys_airy_sys_call
      ...
    """
    linux_base = data["linux_base"]
    lines = []

    lines.append("#")
    lines.append("# Airymax syscalls (%d-%d)" % (linux_base, linux_base + data["core_count"] - 1))
    lines.append("# v1.0.1: 统一使用 %d 起始，避开 x86_64 x32 历史遗留区域（512-547）。" % linux_base)
    lines.append("# 确保在 x86_64/arm64/riscv 所有架构上编号一致，实现跨架构二进制兼容。")
    lines.append("# 设计文档：docs/AirymaxOS/30-interfaces/01-syscalls.md §2.2")
    lines.append("#")
    for sc in data["syscalls"]:
        linux_nr = sc["number"] + linux_base
        lines.append("%d\tcommon\t%s\t\tsys_%s" % (linux_nr, sc["name"], sc["name"]))
    lines.append("")

    return "\n".join(lines)


def generate(input_path, output_path):
    """解析 XML 并生成 C 头文件，返回生成内容字符串。"""
    data = parse_xml(input_path)
    content = render_c_header(data)
    return content


def generate_tbl(input_path):
    """解析 XML 并生成 syscall_64.tbl Airymax 段片段，返回生成内容字符串。"""
    data = parse_xml(input_path)
    content = render_syscall_tbl(data)
    return content


def write_output(content, output_path):
    """将生成内容写入文件。"""
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")
    print("Generated: %s" % out)


def check_mode(input_path, output_path):
    """对比生成内容与已提交文件，diff 不为空则返回非零退出码（CI 集成用）。

    返回值：
      0 — 生成内容与已提交文件一致
      1 — 不一致或已提交文件不存在
    """
    content = generate(input_path, output_path)
    out = Path(output_path)

    if not out.exists():
        print("ERROR: output file does not exist: %s" % out, file=sys.stderr)
        print("       Run 'make syscall' first to generate it." , file=sys.stderr)
        return 1

    existing = out.read_text(encoding="utf-8")
    if existing == content:
        print("OK: generated content matches committed file (%s)" % out)
        return 0

    print("ERROR: generated content differs from committed file: %s" % out, file=sys.stderr)
    print("       Run 'make syscall' to regenerate and commit the result.", file=sys.stderr)
    diff = difflib.unified_diff(
        existing.splitlines(keepends=True),
        content.splitlines(keepends=True),
        fromfile=str(out) + " (committed)",
        tofile=str(out) + " (generated)",
    )
    sys.stderr.writelines(diff)
    return 1


def check_tbl_mode(input_path, tbl_path):
    """对比生成的 tbl 片段与 syscall_64.tbl 中的 Airymax 段，不一致则返回非零退出码。

    返回值：
      0 — Airymax 段与生成内容一致
      1 — 不一致或 tbl 文件不存在
    """
    generated = generate_tbl(input_path)
    tbl_file = Path(tbl_path)

    if not tbl_file.exists():
        print("ERROR: syscall_64.tbl not found: %s" % tbl_file, file=sys.stderr)
        return 1

    tbl_content = tbl_file.read_text(encoding="utf-8")
    if generated in tbl_content:
        print("OK: Airymax tbl section matches generated content (%s)" % tbl_file)
        return 0

    print("ERROR: Airymax tbl section differs from generated content: %s" % tbl_file, file=sys.stderr)
    print("       Expected Airymax section:", file=sys.stderr)
    print(generated, file=sys.stderr)
    return 1


def main():
    parser = argparse.ArgumentParser(
        description="syscall.xml → C UAPI header + syscall_64.tbl generator (R-01 codegen)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""\
示例:
  %(prog)s                          # 生成 syscall_gen.h（使用默认路径）
  %(prog)s --check                  # CI 校验 syscall_gen.h
  %(prog)s --check-tbl              # CI 校验 syscall_64.tbl Airymax 段
  %(prog)s --mode tbl               # 输出 Airymax tbl 片段到 stdout
  %(prog)s -i custom.xml -o out.h   # 自定义输入输出
""",
    )
    parser.add_argument(
        "--input", "-i",
        default=str(DEFAULT_INPUT),
        help="输入 syscall.xml 路径（默认: %(default)s）",
    )
    parser.add_argument(
        "--output", "-o",
        default=str(DEFAULT_OUTPUT),
        help="输出 syscall_gen.h 路径（默认: %(default)s）",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="校验 syscall_gen.h：对比生成内容与已提交文件，diff 不为空则返回非零退出码",
    )
    parser.add_argument(
        "--check-tbl",
        action="store_true",
        help="校验 syscall_64.tbl Airymax 段是否与生成内容一致",
    )
    parser.add_argument(
        "--mode",
        choices=["header", "tbl"],
        default="header",
        help="生成模式：header（C 头文件，默认）或 tbl（syscall_64.tbl 片段）",
    )
    parser.add_argument(
        "--tbl-path",
        default=str(REPO_ROOT / "kernel" / "arch" / "x86" / "entry" / "syscalls" / "syscall_64.tbl"),
        help="syscall_64.tbl 路径（用于 --check-tbl，默认: %(default)s）",
    )
    args = parser.parse_args()

    input_path = Path(args.input).resolve()

    if not input_path.exists():
        print("ERROR: input file not found: %s" % input_path, file=sys.stderr)
        return 1

    if args.check:
        output_path = Path(args.output).resolve()
        return check_mode(input_path, output_path)

    if args.check_tbl:
        tbl_path = Path(args.tbl_path).resolve()
        return check_tbl_mode(input_path, tbl_path)

    if args.mode == "tbl":
        print(generate_tbl(input_path), end="")
        return 0

    output_path = Path(args.output).resolve()
    content = generate(input_path, output_path)
    write_output(content, output_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
